all:
	g++ -std=c++11 -o  main main.cpp	
	g++ -std=c++11 -o test test.cpp
	g++ -std=c++11 -o victorias victorias.cpp
	g++ -std=c++11 -o pred predicciones.cpp

clean:
	rm -f main gen test victorias pred
