all:
	g++ -o main main.cpp
	g++ -o ../Experimentaciones/Estrategia\ para\ llegar\ al\ primer\ lugar/main ../Experimentaciones/Estrategia\ para\ llegar\ al\ primer\ lugar/main.cpp
	#g++ -o gen genRand.cpp
	g++ -o test test.cpp
	g++ -o victorias victorias.cpp
	g++ -o pred predicciones.cpp



clean:
	rm -f main gen test victorias pred
