all:
	g++ -o main main.cpp
	g++ -o main2 main2.cpp
	#g++ -o gen genRand.cpp
	g++ -o test test.cpp
	g++ -o victorias victorias.cpp
	g++ -o pred predicciones.cpp


clean:
	rm -f main gen test victorias pred
